In [3]:
import numpy as np

In [25]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

In [26]:
print(A)
print(B)

[[1 2]
 [7 8]]
[[3 5]
 [1 6]]


In [27]:
Ca = 2+A
Ca

array([[ 3,  4],
       [ 9, 10]])

In [28]:
ab = A+B
ab

array([[ 4,  7],
       [ 8, 14]])

In [29]:
E = A-B
E

array([[-2, -3],
       [ 6,  2]])

In [30]:
print('determinan matriks A = ', np.linalg.det(A))

determinan matriks A =  -6.0


In [31]:
from numpy.linalg import inv

In [51]:
D = np.linalg.inv(B)
D

array([[ 0.46153846, -0.38461538],
       [-0.07692308,  0.23076923]])

In [33]:
mat = np.matmul(D, B)
mat

matrix([[1., 0.],
        [0., 1.]])

In [42]:
print('nilai dan vektor eigen matriks A = ', np.linalg.eig(A)[0])
print('nilai dan vektor eigen matriks A = ', np.linalg.eig(B)[1])

nilai dan vektor eigen matriks A =  [-0.62347538  9.62347538]
nilai dan vektor eigen matriks A =  [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


In [52]:

perkalian_antar_entri = B*D
perkalian_antar_entri

array([[ 1.38461538, -1.92307692],
       [-0.07692308,  1.38461538]])

In [55]:
perkalian_antar_matrix = np.matmul(B,D)
perkalian_antar_matrix

array([[1.00000000e+00, 0.00000000e+00],
       [5.55111512e-17, 1.00000000e+00]])